ipfsImage:
  repo: ipfs/go-ipfs
  tag: v0.10.0

ipfsClusterImage:
  repo: ipfs/ipfs-cluster
  tag: v0.14.1

#secretes example:
#https://cluster.ipfs.io/documentation/guides/k8s/
#od  -vN 32 -An -tx1 /dev/urandom | tr -d ' \n' | base64 -w 0 -
clusterSecret: YzA1NzgxNWEzNjVjNDI0NjU1YjYxNWQ3YjVjNDMwZjI3ZDU3ZjBlMThmOTg3YjU2NGRhZDk2MzM1MTJlNmNkNw==
#go get github.com/whyrusleeping/ipfs-key
#ipfs-key | base64 -w 0
bootstrapPeerPrivateKey: Q0FBU3FRa3dnZ1NsQWdFQUFvSUJBUUNtc2gwYmpENGJ5djNhcTB6VDQva2NjMmMxeEpDSndPZC83VG5WdHNHUEtuaGVmQ2lNeThEZVdsUFNGTytqTUlMN3kzUlYyNUxSOTVzTlVWeDQremgxNXVjcXRZdThmM2U4TlRVM240T29yQW0xYlVXdDkyVEdYYTFsWXprTEhJWldQMTk2Tk9jVEN5VDh5NHh6clR1ZGFiZERzSXdpWUlYMFUydWtUd2tVV2k4V1l6dnVJcHNPajBEV2ZFd0pLcEFmdHRTdFhEWmZYZjdSK215Q0pGNE83aHcwZzFHTEJjaVlGMlpiTE5iT3dJNmw5bnpvWVBzQ1VrWENFRzk2Unhza3BkNUVURk1QeWVJVVRBMWJLQ2Y3ZzRSM0RVVFR0QjZXN090RHpjdjVYVTlDU1p4ejdybS9VQmVxdTNscGVGZXNwTjlnb1IxTWJleFg5SldJSzhhcEFnTUJBQUVDZ2dFQWNNeFg2L3N6VCtWRmNBRzRaQzJBdFNMV05Va0VzV0pxaEdOSFhubGpjdmcvS1ZpRXEvbDRVajMzT0ZKWWNpbnlpR1g5RzlnUCtxcTlMZjdmUHpKbjIwaGJKc2hnZlRZWUZMQkFpWm9VSWovLzlkZXliZXpaTVczVVZxWVV4Sk1SeUN6cjg2cjJyaWs5Wng1cHRTRUZGUmlqSFZmTEM3d2JDT0NtRnpJd0o2ZGpLTzlTb3JvOUprZFozYW9TUHNVc0hoWlFtY3RxQThRY1JaelZHWk5KY0JxTVowVjJxdmd5VnZoOU1nTVJRV3dEazg1NjJOa2srNURJeXFGU2l6UHpFckd0UXNYdTBuVTBnYjcrbXlyak1CdjFEMyt3VjAvRm9MU1NHV3hzOUcxeHpkTUZ1alJPMUFOMFo1b0NMWFBHREhkTUNNVUZCMnI4VVJGN3pMcGE3UUtCZ1FER2xUSDdTdXhvRXZpeVNVNjFIWnFiZTBIYmRBK1FEMjJ2ZkU4WVcrVUtORTRoYW4wTHhMYmtvVmR1anlnYTh2d1NqRFRPelJQbTRyTUpYdWdVV1F3QjhZcllVa0ZhZEZBalBKWld6djUxeHp3emJtYWk1R2ZSUjk5c2tqeEhDU3ZBaHBsR1phWjl0WHd4bDdkS0hJMWpjWFovakxoVTR3NVFWNi9Bd1drZFd3S0JnUURXNUsvbXVtYTFIbGtoRVRMNFhRL1gvY0JzaURHNHFCNy91YnpXdmVwNXBxN0JOVHdzRlhVMUpNNGNLV3NtbDVGYk9mTkpXc1dBd3NVcWUrTVZSWmlDalh2VXVDMDNnL2FnSk5kV05tVktmS1pJRW01bGNXNHVtMmdRTUF6U01GVE4xcG9Zd1RBcGtHUjZiOTkzVnk2T0FmRjV4b1d2VUxyYitxVy93Y2NYU3dLQmdRQ1FWY3g0UzZLOG1sMXNxRit1d0krcFJ0TTlRSVEzUHgrSUZ5QWVJbHk5Si90SnltNk02VFBOeFg4WStyQTV0amFFL0tjOVVFMlEyV0VzQkhGR3FOcFRaMDUxb0lPanpUcWFBZVY3dndPd2MxbE1RSWdWQ1ZKMENIdGFISWYzVWJFZFJEZVB0VDVuekVzeWVJVmVOcGFGbXVoNEdMMjU1VFo0S3VPeGhHSjBWUUtCZ1FDOGZwQkU1TkJlb3FZdnVUUnFZc2NaQUw0ZTlVQVg1M0I1ZytTK3dJdkI5WkZvYkZmQm0zamFDdFM0SXlTWUQyOHpCQndCQmh3a0c3UnkxWVNWRGh6K3R6Z2RtUWdnb0NKZXlySVFMMXFlQWNTaGgzbEtoanJOcXdlVzIyOERsOTFyU0lpV21pNnk1ck1jS3JGcnJ3OXBCUTlaYitlbnBqcWg1clFwQmNLckRRS0JnUUNNZjlIRmlKRENhaGxiL3QrSURTdTFlT09YNjRLYVUzcHpTUmUzQVhsaFJpbkkyK0tpcy9xWCtsNjRkVmJ1eVhoQVlMTFljRjRjdlU2SXlCODZFVzVDck5BTUpkMms0Q1VISzAxZHpDNXNNdTQrR0NQV2pCL1I2Wnd2R1lyb0ZnQUJqMytTUGlaV1RybytnWStEN0FGNkxaWDJUbnhFMUtlc3RMVXlSOWNOc1E9PQo=
#echo "<INSERT_PRIV_KEY_VALUE_HERE>" | base64 -w 0 -
bootstrapPeerId: QmfBjL2kDjr34JbTLquxJE7d8gNbMuRmLbDuyHPQcebSgV

replicaCount: 1

persistance:
  enabled: true
  clusterStorage: 5Gi
  ipfsStorage: 200Gi