{{- if and .Values.ingress.gateway.basicAuth.enabled }}
apiVersion: v1
data:
  auth: {{ .Values.ingress.gateway.basicAuth.htpasswd }}
kind: Secret
metadata:
  name: {{ .Values.ingress.gateway.basicAuth.secretName }}
type: Opaque
{{- end }}
