environments:
  ci:
  local:
  production:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

# - name: ipfs-cluster
#   chart: ../charts/ipfs-cluster
#   values:
#     - ./config/ipfs-cluster-values.yaml.gotmpl

- name: ipfs-cluster
  chart: w3f/ipfs-cluster
  values:
    - ./config/ipfs-cluster-values.yaml.gotmpl
