{{- if .Values.ingress.gateway.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  {{- with .Values.ingress.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.gateway.host }}
    http:
      paths:
      - path: /(.+)
        pathType: Prefix
        backend:
          service:
            name: {{ include "ipfs-cluster.serviceNameHttp" . }}
            port:
              name: gateway
{{- end }}
{{- if .Values.ingress.clusterApi.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cluster-api
  {{- with .Values.ingress.clusterApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.clusterApi.host }}
    http:
      paths:
      - path: /(.+)
        pathType: Prefix
        backend:
          service:
            name: {{ include "ipfs-cluster.serviceNameHttp" . }}
            port:
              name: api-http
{{- end }}
