apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipfs-cluster.secretName" . }}
type: Opaque
data:
  cluster-secret: {{ .Values.clusterSecret }}
  bootstrap-peer-priv-key: {{ .Values.bootstrapPeerPrivateKey }}