apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceName" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ipfs.w3f.community
  labels:
    node: {{ .Release.Name }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: swarm
    targetPort: swarm
    port: 4001
  - name: swarm-udp
    targetPort: swarm-udp
    port: 4002
  - name: ws
    targetPort: ws
    port: 8081
  - name: http
    targetPort: http
    port: 8080
  - name: api-http
    targetPort: api-http
    port: 9094
  - name: proxy-http
    targetPort: proxy-http
    port: 9095
  - name: cluster-swarm
    targetPort: cluster-swarm
    port: 9096
  # - name: api
  #   targetPort: api
  #   port: 5001  
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceNameHttp" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - name: api
    targetPort: api
    port: 5001
  selector:
    app: {{ .Release.Name }}  