---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceName" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: swarm
    targetPort: 4001
    port: 4001
    protocol: TCP
  - name: swarm-udp
    targetPort: 4002
    port: 4002
    protocol: TCP
  - name: cluster-swarm
    targetPort: 9096
    port: 9096
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.serviceName" . }}-http
  labels:
    node: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: gateway
    targetPort: 8080
    port: 8080
    protocol: TCP
  - name: api
    targetPort: 5001
    port: 5001
    protocol: TCP
  - name: api-http
    targetPort: 9094
    port: 9094
    protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "ipfs-cluster.serviceName" . }}-local
#  labels:
#    node: {{ .Release.Name }}
#spec:
#  selector:
#    app: {{ .Release.Name }}
#  ports:
#  - name: api
#    targetPort: 5001
#    port: 5001
#    protocol: TCP
#  - name: proxy-http
#    targetPort: 9095
#    port: 9095
#    protocol: TCP
#  - name: ws
#    targetPort: 8081
#    port: 8081
#    protocol: TCP
#  - name: api-http
#    targetPort: 9094
#    port: 9094
#    protocol: TCP
